"""initial_schema

Revision ID: 1ccf320cae19
Revises: 
Create Date: 2026-09-13 21:45:14.236060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccf320cae19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('routing_keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'officer', 'admin', name='user_role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('complaints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('voice_note_url', sa.String(length=1024), nullable=True),
    sa.Column('detected_issue_type', sa.Enum('pothole', 'garbage', 'water_leakage', 'broken_streetlight', 'other', name='issue_type'), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'acknowledged', 'in_progress', 'resolved', 'rejected', 'duplicate', name='complaint_status'), nullable=False),
    sa.Column('duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('needs_manual_category', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_citizen_id'), 'complaints', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_complaints_department_id'), 'complaints', ['department_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'acknowledged', 'in_progress', 'resolved', 'rejected', 'duplicate', name='status_history_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_changed_at'), 'status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_status_history_complaint_id'), 'status_history', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_complaint_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_changed_at'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_department_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_citizen_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
